// const suites = []
// suites.push(require('./coalescing-to-md'))
// suites.push(require('./performance-testing'))
// suites.push(require('./reporter-order'))
// suites.push(require('./runners/multiple-suites'))
// suites.push(require('./runners/named-suites'))
// suites.push(require('./runners/setup-teardown'))
// suites.push(require('./runners/skipping-file-discovery'))
// suites.push(require('./runners/skipping-file-discovery-browser'))
// suites.push(require('./runners/skipping-file-discovery-plan'))
// suites.push(require('./runners/using-browser-test-server'))
// suites.push(require('./runners/using-nodejs-runner'))
// suites.push(require('./runners/using-nodejs-runner-with-injection'))
// suites.push(require('./Suites-setup-teardown'))
// suites.push(require('./writing-a-reporter'))
// suites.push(require('./custom-dsl'))
// suites.push(require('./Suites'))
// suites.push(require('./using-async-await'))
// suites.push(require('./using-promises'))
//
// Promise.all(suites)
//   .then((results) => {
//     console.log(results)
//   })
