# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: ENVVARS
      env:
        EVENT_CONTEXT: ${{ toJson(github.event) }}
      run: |
        echo "node: $(node --version)"
        echo "npm: $(npm --version)"
      # echo "EVENT_CONTEXT:"
      # echo "$EVENT_CONTEXT"

    - name: Install Packages
      run: |
        npm i -g pnpm
        pnpm install

    - name: Lint the repo
      run: pnpm run lint

    - name: Run Tests
      env:
        CI: true
      run: pnpm run test:coverage:ci
